version: "3"

services:
  pyopenms:
    image: dmccloskey/docker-pyopenms-vscode:develop
    volumes:
      ## Input/Output file directory
      - //C/Users/domccl/Desktop/GoldenLab_180619/:/home/user/Data/
      ## EXE directory
      - //C/Users//domccl/GitHub/smartPeak/:/home/user/code/
    ports:
      - "3000:3000"
    command: python /home/user/code/debug_remote.py #testing
    # command: python /home/user/code/debug_local.py
    restart: always
    networks:
      - pyopenms_network
    
networks:
  pyopenms_network:
    ipam:
      config:
        - subnet: 172.22.0.0/16