version: "3"

services:
  pyopenms:
    # image: dmccloskey/smartpeak:latest
    image: dmccloskey/docker-pyopenms-vscode:develop
    volumes:
      ## Input/Output file directory
      # WIN:
      # - //C/Users/domccl/Dropbox (UCSD SBRG)/Project_SmartPeak/SGI_demo_01/RO_Anions_Quant/:/home/user/Data/
      # - //C/Users/domccl/Dropbox (UCSD SBRG)/Project_SmartPeak/SGI_demo_01/RO_Anions_MID/:/home/user/Data/
      # - //C/Users/domccl/Dropbox (UCSD SBRG)/Project_SmartPeak/SGI_demo_01/RO_Cations_Quant/:/home/user/Data/
      # - //C/Users/domccl/Dropbox (UCSD SBRG)/Project_SmartPeak/SGI_demo_01/RO_Cations_MID/:/home/user/Data/
      # - //C/Users/domccl/Dropbox (UCSD SBRG)/Project_SmartPeak/SGI_demo_02/2017_05_08_Anions/:/home/user/Data/
      # - //C/Users/domccl/Dropbox (UCSD SBRG)/Project_SmartPeak/SGI_demo_02/2017_05_10_Cations/:/home/user/Data/
      # - //C/Users/domccl/Dropbox (UCSD SBRG)/Project_SmartPeak/SGI_demo_02/2017_05_12_Cations_pH9-7/:/home/user/Data/
      # - //C/Users/domccl/Dropbox (UCSD SBRG)/Project_SmartPeak/SGI_demo_03/2016_09_20_Anions/:/home/user/Data/
      # - //C/Users/domccl/Dropbox (UCSD SBRG)/Project_SmartPeak/SGI_demo_03/2016_09_24_Cations/:/home/user/Data/
      # - //C/Users/domccl/Dropbox (UCSD SBRG)/Project_SmartPeak/SGI_demo_03/2016_10_01_Cations_pH9-7/:/home/user/Data/
      # - //C/Users/domccl/GitHub/smartPeak/:/home/user/code/

      # - //C/Users/dmccloskey/Dropbox (UCSD SBRG)/Project_SmartPeak/SGI_demo_01/RO_Anions_Quant/:/home/user/Data/
      # - //C/Users/dmccloskey/Dropbox (UCSD SBRG)/Project_SmartPeak/SGI_demo_01/RO_Anions_MID/:/home/user/Data/
      # - //C/Users/dmccloskey/Dropbox (UCSD SBRG)/Project_SmartPeak/SGI_demo_01/RO_Cations_Quant/:/home/user/Data/
      # - //C/Users/dmccloskey/Dropbox (UCSD SBRG)/Project_SmartPeak/SGI_demo_01/RO_Cations_MID/:/home/user/Data/
      # - //C/Users/dmccloskey/Dropbox (UCSD SBRG)/Project_SmartPeak/SGI_demo_02/2017_05_08_Anions/:/home/user/Data/
      # - //C/Users/dmccloskey/Dropbox (UCSD SBRG)/Project_SmartPeak/SGI_demo_02/2017_05_10_Cations/:/home/user/Data/
      # - //C/Users/dmccloskey/Dropbox (UCSD SBRG)/Project_SmartPeak/SGI_demo_02/2017_05_12_Cations_pH9-7/:/home/user/Data/
      - //C/Users/dmccloskey/Dropbox (UCSD SBRG)/Project_SmartPeak/SGI_demo_03/2016_09_20_Anions/:/home/user/Data/
      # - //C/Users/dmccloskey/Dropbox (UCSD SBRG)/Project_SmartPeak/SGI_demo_03/2016_09_24_Cations/:/home/user/Data/
      # - //C/Users/dmccloskey/Dropbox (UCSD SBRG)/Project_SmartPeak/SGI_demo_03/2016_10_01_Cations_pH9-7/:/home/user/Data/
      - //C/Users/dmccloskey/Documents/GitHub/smartPeak/:/home/user/code/
    ports:
      - "3000:3000"
    # command: python /home/user/code/debug_remote.py #testing
    command: python /home/user/code/main.py
    networks:
      - pyopenms_network
    
networks:
  pyopenms_network:
    ipam:
      config:
        - subnet: 172.22.0.0/16