version: "3"

services:
  pyopenms:
    image: dmccloskey/smartpeak:latest
    volumes:
      ## Input/Output file directory
      # WIN:
      - //C/Users/dmccloskey/Desktop/LCMS_MRM/:/home/user/Data/
      # LINUX/MAC
      # - /home/systemsbiochemistry1/Documents/Data/:/home/user/Data/
    ports:
      - "3000:3000"
    command: python /home/user/code/main.py
    networks:
      - pyopenms_network
    
networks:
  pyopenms_network:
    ipam:
      config:
        - subnet: 172.22.0.0/16