version: "3"

services:
  openms:
    image: dmccloskey/docker-openms-vscode
    volumes:
      - //C/Users/domccl/Dropbox (UCSD SBRG)/Project_FastPeak/openMS_MRMworkflow/:/home/user/openMS_MRMworkflow/
      - //C/Users//domccl/GitHub/smartPeak/:/home/user/code/
    ports:
      - "3000:3000"
    security_opt:
      - seccomp:unconfined
    #command: python /home/user/code/debug_remote.py
    restart: always
    networks:
      - openms_network
    
networks:
  openms_network:
    ipam:
      config:
        - subnet: 172.22.0.0/16